### ISSUE TITLE
Can not reproduce reported De->En IWSLT scores

### ISSUE THREAD

**Issue by nathanielhobbs** [fe1ixxu/BiBERT#4]
I've cloned this repository, and followed the instructions as far as I can tell to the letter: 
- installed all the prerequisites as in the readme
-  downloaded the pre-trained bilingual English-German BiBERT
-  ran download_and_prepare_data.sh
-  trained models using train.sh and train-dual.sh (keeping update-freq=4 as I'm training on a system with 4 GPUs)
-  generated text according to generate.sh and generate-dual.sh.
The above by default is in the De->En direction.

I have in fact trained the system multiple times, and each time I'm getting a lower BLEU (about 3 points lower) than you report in the paper (reported 38.12 BLEU for the fine-tuned model).

Running generate-dual.sh, Here is a representative example of the last two lines of generate.out:
2023-11-28 15:07:43 | INFO | fairseq_cli.generate | Translated 6750 sentences (143040 tokens) in 25.5s (265.05 sentences/s, 5616.80 tokens/s)
2023-11-28 15:07:43 | WARNING | fairseq_cli.generate | BLEU score is being computed by splitting detokenized string on spaces, this is probably not what you want. Use --sacrebleu for standard 13a BLEU tokenization
Generate test with beam=4: BLEU4 = 35.12, 70.1/44.9/30.8/21.4 (BP=0.925, ratio=0.928, syslen=126357, reflen=136218)

Adding --sacrebleu to the fairseq-generate command, I get:
2023-11-28 14:52:25 | INFO | fairseq_cli.generate | Translated 6750 sentences (146280 tokens) in 27.0s (250.19 sentences/s, 5421.81 tokens/s)
Generate test with beam=4: BLEU4 = 35.30, 69.1/44.1/30.1/21.0 (BP=0.947, ratio=0.949, syslen=129225, reflen=136218)

Is there some step that I'm missing?

**Comment by fe1ixxu** [comment]
Hi, thanks for your interest!

Since you basically follow all the instructions, I suspect it may be related to the version of `transformers`. Could you please share your `transformers` version? My suggestion could be first trying to roll back to an old version of `transformers`, say, `4.4.2`, and try to run the model again.

Many people have successfully reproduced better results than reported in the paper. I hope this could help you get the same positive results!

**Comment by nathanielhobbs** [comment]
You are correct, I was using transformers version 4.30.2.

However, when I upgrade to transformers v. 4.4.2 I'm now getting a different running train-dual.sh:
bash train-dual.sh
Traceback (most recent call last):
  File "/home/nh385/anaconda3/envs/bibert/bin/fairseq-train", line 5, in <module>
    from fairseq_cli.train import cli_main
  File "/projectsp/f_jsvaidya_1/BiBERT/fairseq_cli/train.py", line 21, in <module>
    from fairseq import (
  File "/projectsp/f_jsvaidya_1/BiBERT/fairseq/__init__.py", line 20, in <module>
    import fairseq.models  # noqa
  File "/projectsp/f_jsvaidya_1/BiBERT/fairseq/models/__init__.py", line 175, in <module>
    module = importlib.import_module("fairseq.models." + model_name)
  File "/home/nh385/anaconda3/envs/bibert/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/projectsp/f_jsvaidya_1/BiBERT/fairseq/models/nat/__init__.py", line 7, in <module>
    from .fairseq_nat_model import *
  File "/projectsp/f_jsvaidya_1/BiBERT/fairseq/models/nat/fairseq_nat_model.py", line 9, in <module>
    from fairseq.models.transformer import (
  File "/projectsp/f_jsvaidya_1/BiBERT/fairseq/models/transformer.py", line 35, in <module>
    from transformers import AutoModel
  File "/home/nh385/anaconda3/envs/bibert/lib/python3.7/site-packages/transformers/__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "/home/nh385/anaconda3/envs/bibert/lib/python3.7/site-packages/transformers/dependency_versions_check.py", line 41, in <module>
    require_version_core(deps[pkg])
  File "/home/nh385/anaconda3/envs/bibert/lib/python3.7/site-packages/transformers/utils/versions.py", line 94, in require_version_core
    return require_version(requirement, hint)
  File "/home/nh385/anaconda3/envs/bibert/lib/python3.7/site-packages/transformers/utils/versions.py", line 85, in require_version
    if want_ver is not None and not ops[op](version.parse(got_ver), version.parse(want_ver)):
  File "/home/nh385/anaconda3/envs/bibert/lib/python3.7/site-packages/packaging/version.py", line 54, in parse
    return Version(version)
  File "/home/nh385/anaconda3/envs/bibert/lib/python3.7/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'

I re-cloned again the repository and doing everything as before, except for forcing the version of transformers by running "pip install transformers==4.4.2".If it's relevant, running pip --version produces  "pip 23.3.1 from /home/<<my_username>>/anaconda3/envs/bibert/lib/python3.7/site-packages/pip (python 3.7)".  

Under this "starting from scratch" circumstance, then during the data pre-processing stage I get a similar error error running download_and_prepare_data.sh: 
creating train, valid, test...
learn_bpe.py on iwslt14.tokenized.de-en/tmp/train.en-de...
100%|####################################################################################################################################################################| 10000/10000 [00:22<00:00, 435.85it/s]
apply_bpe.py to train.de...
apply_bpe.py to valid.de...
apply_bpe.py to test.de...
apply_bpe.py to train.en...
apply_bpe.py to valid.en...
apply_bpe.py to test.en...
Traceback (most recent call last):
  File "vocab_trainer.py", line 4, in <module>
    from transformers import BertTokenizer
  File "/home/nh385/anaconda3/envs/bibert2/lib/python3.7/site-packages/transformers/__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "/home/nh385/anaconda3/envs/bibert2/lib/python3.7/site-packages/transformers/dependency_versions_check.py", line 41, in <module>
    require_version_core(deps[pkg])
  File "/home/nh385/anaconda3/envs/bibert2/lib/python3.7/site-packages/transformers/utils/versions.py", line 94, in require_version_core
    return require_version(requirement, hint)
  File "/home/nh385/anaconda3/envs/bibert2/lib/python3.7/site-packages/transformers/utils/versions.py", line 85, in require_version
    if want_ver is not None and not ops[op](version.parse(got_ver), version.parse(want_ver)):
  File "/home/nh385/anaconda3/envs/bibert2/lib/python3.7/site-packages/packaging/version.py", line 54, in parse
    return Version(version)
  File "/home/nh385/anaconda3/envs/bibert2/lib/python3.7/site-packages/packaging/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: '0.10.1,<0.11'

**Comment by nathanielhobbs** [comment]
I've upgraded to transformers 2.6 and this has resolved the above issue regarding the error.  I will update again once training finishes for confirmation that I'm able to achieve the baseline you reported.

**Comment by Desperat1on** [comment]
I have a question. How should I modify download_and_prepare_data.sh if I want to get the one-way data of en->de?

**Comment by fe1ixxu** [comment]
> I have a question. How should I modify download_and_prepare_data.sh if I want to get the one-way data of en->de?

Hello, there's no need for you to take any additional actions. Simply utilize the data located in the `./data` folder, where you'll find `train.en` and `train.de` as parallel datasets. You're free to proceed in either the direction of translating en->de or from de->en.
